# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-13 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0004_auto_20190112_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bm', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('slug', models.SlugField(default='will-be-generated-once-save')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(to='limau.RecipeTag'),
        ),
    ]
